# 应用服务器
server:
  tomcat:
    uri-encoding: UTF-8
  port: 30006

# Spring
spring:
  profiles:
    # 环境配置
    active: dev
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    # 开启在线日志查看功能
    logfile:
      enabled: true
