# 应用服务器
server:
  tomcat:
    uri-encoding: UTF-8
  port: 30001

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    # 开启在线日志查看功能
    logfile:
      enabled: true


